version: '3'
services:
  build: .
  entrypoint: ./docker/entrypoint.sh
  container_name: nestjs-app
  ports:
    - "3000:3000"
  volumes:
    - .:/home/node/app
  depends_on:
    - db
  network_mode: bridge
  
  db:
    image: postgres
    container_name: postgres-db
    restart: always
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=zrcQqid1kSXUM590EJ4Yo126
      - POSTGRES_DB=ads_db

volumes:
  pgdata:
